name: Bug report
description: Report a reproducible defect.
title: "[Bug]: "
labels:
  - bug
body:
  - type: markdown
    attributes:
      value: |
        Thanks for reporting a bug.
        For security-sensitive reports, use private vulnerability reporting instead of public issues.
  - type: textarea
    id: summary
    attributes:
      label: Summary
      description: What happened and what did you expect?
    validations:
      required: true
  - type: textarea
    id: steps
    attributes:
      label: Reproduction steps
      description: Provide exact commands or inputs.
      placeholder: |
        1. Run ...
        2. Execute ...
        3. Observe ...
    validations:
      required: true
  - type: input
    id: version
    attributes:
      label: Version
      description: Output of `./bin/agentsec version` or commit SHA.
    validations:
      required: true
  - type: textarea
    id: logs
    attributes:
      label: Logs / output
      description: Paste relevant output.
      render: shell
